In [2]:
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName('ops').getOrCreate()

In [4]:
df = spark.read.csv('appl_stock.csv', inferSchema=True, header=True)
df.show()

+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|               Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04 00:00:00|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05 00:00:00|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06 00:00:00|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07 00:00:00|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08 00:00:00|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11 00:00:00|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12 00:00:00|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13 00:00:00|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14 00:00:00|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15 00:00:00|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19 00:00:00|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20 00:00:00|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21 00:00:00|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22 00:00:00|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25 00:00:00|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26 00:00:00|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27 00:00:00|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28 00:00:00|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29 00:00:00|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01 00:00:00|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [5]:
df.printSchema()

root
 |-- Date: timestamp (nullable = true)
 |-- Open: double (nullable = true)
 |-- High: double (nullable = true)
 |-- Low: double (nullable = true)
 |-- Close: double (nullable = true)
 |-- Volume: integer (nullable = true)
 |-- Adj Close: double (nullable = true)

In [10]:
df.show()

+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|               Date|              Open|              High|               Low|             Close|   Volume|         Adj Close|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
|2010-01-04 00:00:00|        213.429998|        214.499996|212.38000099999996|        214.009998|123432400|         27.727039|
|2010-01-05 00:00:00|        214.599998|        215.589994|        213.249994|        214.379993|150476200|27.774976000000002|
|2010-01-06 00:00:00|        214.379993|            215.23|        210.750004|        210.969995|138040000|27.333178000000004|
|2010-01-07 00:00:00|            211.75|        212.000006|        209.050005|            210.58|119282800|          27.28265|
|2010-01-08 00:00:00|        210.299994|        212.000006|209.06000500000002|211.98000499999998|111902700|         27.464034|
|2010-01-11 00:00:00|212.79999700000002|        213.000002|        208.450005|210.11000299999998|115557400|         27.221758|
|2010-01-12 00:00:00|209.18999499999998|209.76999500000002|        206.419998|        207.720001|148614900|          26.91211|
|2010-01-13 00:00:00|        207.870005|210.92999500000002|        204.099998|        210.650002|151473000|          27.29172|
|2010-01-14 00:00:00|210.11000299999998|210.45999700000002|        209.020004|            209.43|108223500|         27.133657|
|2010-01-15 00:00:00|210.92999500000002|211.59999700000003|        205.869999|            205.93|148516900|26.680197999999997|
|2010-01-19 00:00:00|        208.330002|215.18999900000003|        207.240004|        215.039995|182501900|27.860484999999997|
|2010-01-20 00:00:00|        214.910006|        215.549994|        209.500002|            211.73|153038200|         27.431644|
|2010-01-21 00:00:00|        212.079994|213.30999599999998|        207.210003|        208.069996|152038600|         26.957455|
|2010-01-22 00:00:00|206.78000600000001|        207.499996|            197.16|            197.75|220441900|         25.620401|
|2010-01-25 00:00:00|202.51000200000001|        204.699999|        200.190002|        203.070002|266424900|26.309658000000002|
|2010-01-26 00:00:00|205.95000100000001|        213.710005|        202.580004|        205.940001|466777500|         26.681494|
|2010-01-27 00:00:00|        206.849995|            210.58|        199.530001|        207.880005|430642100|26.932840000000002|
|2010-01-28 00:00:00|        204.930004|        205.500004|        198.699995|        199.289995|293375600|25.819922000000002|
|2010-01-29 00:00:00|        201.079996|        202.199995|        190.250002|        192.060003|311488100|         24.883208|
|2010-02-01 00:00:00|192.36999699999998|             196.0|191.29999899999999|        194.729998|187469100|         25.229131|
+-------------------+------------------+------------------+------------------+------------------+---------+------------------+
only showing top 20 rows

In [13]:
#Filter rows based on conditions
df.filter("Open < 100").filter("Close < 92").show()

+-------------------+---------+-----------------+---------+-----------------+---------+-----------------+
|               Date|     Open|             High|      Low|            Close|   Volume|        Adj Close|
+-------------------+---------+-----------------+---------+-----------------+---------+-----------------+
|2014-06-13 00:00:00|92.199997|        92.440002|90.879997|        91.279999| 54525000|        86.610132|
|2014-06-19 00:00:00|92.290001|        92.300003|91.339996|        91.860001| 35528000|        87.160461|
|2014-06-20 00:00:00|91.849998|        92.550003|90.900002|        90.910004|100898000|        86.259066|
|2014-06-23 00:00:00|    91.32|        91.620003|90.599998|90.83000200000001| 43694000|        86.183157|
|2014-06-24 00:00:00|    90.75|        91.739998|90.190002|        90.279999| 39036000|        85.661292|
|2014-06-25 00:00:00|90.209999|        90.699997|89.650002|        90.360001| 36869000|        85.737201|
|2014-06-26 00:00:00|90.370003|        91.050003|89.800003|        90.900002| 32629000|        86.249576|
|2014-06-27 00:00:00|    90.82|             92.0|90.769997|        91.980003| 64029000|        87.274325|
|2016-05-12 00:00:00|92.720001|        92.779999|89.470001|        90.339996| 76314700|         89.00837|
|2016-05-13 00:00:00|     90.0|91.66999799999999|     90.0|        90.519997| 44392800|89.18571700000001|
+-------------------+---------+-----------------+---------+-----------------+---------+-----------------+

In [17]:
df.filter("Open < 100").filter("Close < 92").select(["Open", "Close", "Volume"]).show()

+---------+-----------------+---------+
|     Open|            Close|   Volume|
+---------+-----------------+---------+
|92.199997|        91.279999| 54525000|
|92.290001|        91.860001| 35528000|
|91.849998|        90.910004|100898000|
|    91.32|90.83000200000001| 43694000|
|    90.75|        90.279999| 39036000|
|90.209999|        90.360001| 36869000|
|90.370003|        90.900002| 32629000|
|    90.82|        91.980003| 64029000|
|92.720001|        90.339996| 76314700|
|     90.0|        90.519997| 44392800|
+---------+-----------------+---------+

In [18]:
#Different way of filtering multiple conditions
df.filter(df['Open'] < 100).filter(df['Close'] < 92).select(["Open", "Close", "Volume"]).show()

+---------+-----------------+---------+
|     Open|            Close|   Volume|
+---------+-----------------+---------+
|92.199997|        91.279999| 54525000|
|92.290001|        91.860001| 35528000|
|91.849998|        90.910004|100898000|
|    91.32|90.83000200000001| 43694000|
|    90.75|        90.279999| 39036000|
|90.209999|        90.360001| 36869000|
|90.370003|        90.900002| 32629000|
|    90.82|        91.980003| 64029000|
|92.720001|        90.339996| 76314700|
|     90.0|        90.519997| 44392800|
+---------+-----------------+---------+

In [25]:
#Filter rows based on multiple conditions
df.filter((df['Open'] < 100) & (df['Close'] < 92)).select(["Open", "Close", "Volume"]).show()

+---------+-----------------+---------+
|     Open|            Close|   Volume|
+---------+-----------------+---------+
|92.199997|        91.279999| 54525000|
|92.290001|        91.860001| 35528000|
|91.849998|        90.910004|100898000|
|    91.32|90.83000200000001| 43694000|
|    90.75|        90.279999| 39036000|
|90.209999|        90.360001| 36869000|
|90.370003|        90.900002| 32629000|
|    90.82|        91.980003| 64029000|
|92.720001|        90.339996| 76314700|
|     90.0|        90.519997| 44392800|
+---------+-----------------+---------+

In [27]:
#Equality check
df.filter(df['Low'] == 197.16).show()

+-------------------+------------------+----------+------+------+---------+---------+
|               Date|              Open|      High|   Low| Close|   Volume|Adj Close|
+-------------------+------------------+----------+------+------+---------+---------+
|2010-01-22 00:00:00|206.78000600000001|207.499996|197.16|197.75|220441900|25.620401|
+-------------------+------------------+----------+------+------+---------+---------+

In [35]:
#Collect the results
result = df.filter(df['Low'] == 197.16).collect()
result

[Row(Date=datetime.datetime(2010, 1, 22, 0, 0), Open=206.78000600000001, High=207.499996, Low=197.16, Close=197.75, Volume=220441900, Adj Close=25.620401)]

In [39]:
#Process the collected result
row = result[0]
row.asDict()['High']

207.499996